export const layoutComponents = [
  {
    label: '多页签',
    type: 'tabs',
    default: '',
    key: null,
    icon: '',
    w: 24,
    h: 30,
    columns: [
      {
        name: '页签一',
        key: null,
        list: [],
        showCondition: '',
      },
      {
        name: '页签二',
        key: null,
        list: [],
        showCondition: '',
      },
    ],
    control: {
      type: 'border-card',
    },
  },
  {
    type: 'grid',
    label: '格栅布局',
    icon: 'grid',
    key: null,
    w: 24,
    h: 30,
    columns: [
      // 格栅列数据
      {
        attr: { w: 12 },
        key: null,
        list: [],
      },
      {
        attr: { w: 12 },
        key: null,
        list: [],
      },
    ],
    control: {},
  },
  {
    type: 'collapse',
    label: '折叠面板',
    icon: 'collapse',
    expand: ['collapse'],
    w: 24,
    h: 30,
    key: '',
    columns: [
      {
        name: '折叠面板',
        key: 'collapse',
        list: [],
        showCondition: '',
      },
    ],
    control: {},
  },
  {
    type: 'card',
    label: '卡片布局',
    icon: 'card',
    key: '',
    w: 24,
    h: 30,
    list: [],
    control: {},
  },
]

export const commonCompon = [
  {
    type: 'divider',
    label: '分割线',
    icon: 'divider',
    key: '',
    w: 24,
    h: 5,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    control: {
      align: 'left',
    },
  },
  {
    type: 'title',
    label: '标题',
    icon: 'title',
    key: '',
    h: 5,
    w: 24,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    control: {
      align: 'center',
    },
  },
  {
    type: 'tip',
    label: '提示',
    icon: 'tip',
    key: '',
    control: {
      text:'提示 ',
      textType:'info',
      effect:'light',
      showIcon:true,
      align: 'left',
    },
    h: 7,
    w: 24,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
  },
  {
    label: '图标菜单',
    type: 'AbIcoinButton',
    key: null,
    icon: '',
    w: 24,
    h: 15,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbIcoinButton',
  },
  {
    label: '图片&轮播',
    type: 'AbPictureConfig',
    key: null,
    icon: '',
    control: {},
    w: 24,
    h: 20,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbPictureLayout',
  },
  {
    label: '过滤组件',
    type: 'AbFilterConfig',
    key: null,
    icon: '',
    control: {},
    h: 7,
    w: 24,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbFilterLayout',
  },
  {
    label: '工具条',
    type: 'AbToolbar',
    key: null,
    icon: '',
    w: 24,
    h: 7,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    control: {},
    component: 'AbToolbarLayout',
  },
  {
    label: '富文本',
    type: 'AbRichEditorConfig',
    key: null,
    h: 50,
    w: 24,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbRich',
    control: {},
  },
]

export const bizCompon = [
  {
    label: '在线表单',
    type: 'AbCustFormComponent',
    key: null,
    icon: '',
    control: { refreshCycle: 10 },
    h: 50,
    w: 24,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbCustFormLayout',
  },
  {
    label: '应用列表',
    type: 'AbCustomListComponent',
    key: null,
    icon: '',
    control: { refreshCycle: 10 },
    h: 50,
    w: 24,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbCustomListLayout',
  },
  {
    label: '外部页面',
    type: 'AbFormIfream',
    key: null,
    icon: '',
    w: 24,
    h: 50,
    control: { refreshCycle: 10 },
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbFormIfream',
  },

  {
    label: '流程待办',
    type: 'AbTodoTaskConfig',
    key: null,
    icon: '',
    control: {
      refreshCycle: 10,
      condition: '',
      type: '',
      param: [
        {
          code: 'todoTask',
          type: '待办事项',
          title: '待办事项',
          count: 8,
          default: true,
          enable: true,
          showTime: true,
        },
        {
          code: 'approve',
          type: '办理历史',
          title: '办理历史',
          count: 8,
          default: false,
          enable: true,
          showTime: true,
        },
        {
          code: 'carbonCopy',
          type: '我的抄送',
          title: '我的抄送',
          count: 8,
          default: false,
          enable: true,
          showTime: true,
        },
      ],
    },
    h: 46,
    w: 12,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbTodoTask',
  },
]

export const chartCompon = [
  {
    label: '甘特图',
    type: 'AbGanttChartConfig',
    key: null,
    icon: '',
    control: { refreshCycle: 10 },
    h: 50,
    w: 24,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbGanttChartLayout',
  },
  {
    label: '地图',
    type: 'AbMapConfig',
    key: null,
    control: {
      fontStyle: 0,
      mapCode: '100000',
      toolColor: '#c50000',
      refreshCycle: 10,
    },
    h: 50,
    w: 24,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbMap',
  },
  {
    label: '柱形图',
    type: 'AbBarEcharts',
    key: null,
    icon: '',
    control: { refreshCycle: 10 },
    h: 30,
    w: 8,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbBarEcharts',
  },
  {
    label: '饼形图',
    type: 'AbPieEcharts',
    key: null,
    icon: '',
    control: { refreshCycle: 10 },
    h: 30,
    w: 8,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbPieEcharts',
  },
  {
    label: '折线图',
    type: 'AbLineEcharts',
    key: null,
    icon: '',
    control: { refreshCycle: 10 },
    h: 30,
    w: 8,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbLineEcharts',
  },
  {
    label: '区域图',
    type: 'AbAreaEcharts',
    key: null,
    icon: '',
    control: { refreshCycle: 10 },
    h: 30,
    w: 8,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbAreaEcharts',
  },
  {
    label: '沙漏图',
    type: 'AbFunnelEcharts',
    key: null,
    icon: '',
    control: { refreshCycle: 10 },
    h: 30,
    w: 8,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbFunnelEcharts',
  },
  {
    label: '指标卡',
    type: 'AbIndicatorCard',
    key: null,
    icon: '',
    control: { refreshCycle: 10 },
    h: 11,
    w: 6,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbIndicatorCard',
  },
  {
    label: '流程指标卡',
    type: 'AbBpmIndicatorCardConfig',
    key: null,
    icon: '',
    control: { condition: '', refreshCycle: 10 },
    h: 11,
    w: 24,
    backgroundType: 'color',
    backgroundColor: '',
    backgroundPicture: '',
    backgroundTransparency: 1,
    tcType: 0,
    component: 'AbBpmIndicatorCard',
  },
]

import collapseConfig from './collapseConfig.vue'
import tabsConfig from './tabsConfig.vue'
import abFormIfreamConfig from '../components/abFormIfream/config.vue'
import AbToolbarConfig from '../components/abToolbar/abToolbarConfig.vue'
import AbIcoinButtonConfig from '../components/abIcoinButton/config.vue'
import AbCustFormComponent from '../components/abCustForm/abCustFormConfig.vue'
import AbCustomListComponent from '../components/abCustomList/abCustomListConfig.vue'
import Test from '../components/Test/index.vue'
import AbPictureConfig from '../components/abPicture/config.vue'
import AbFilterConfig from '../components/abFilter/config.vue'
import AbEchartsConfig from '../components/abEcharts/config.vue'
import AbIndicatorCardConfig from '../components/abIndicatorCard/config.vue'
import AbBpmIndicatorCardConfig from '../components/abBpmIndicatorCard/config.vue'
import AbGanttChartConfig from '../components/abGanttChart/config.vue'
import AbTodoTaskConfig from '../components/abTodoTask/config.vue'
import AbMapConfig from '../components/abMap/config.vue'
import AbRichEditorConfig from '../components/abRichEditor/config.vue'
//import AbAlertConfig from '../components/abAlert/abAlertConfig.vue'
// 组件配置页面 配置
export const componentConfigPage = {
  // Ifream 组件配置页面
  collapse: markRaw(collapseConfig),
  tabs: markRaw(tabsConfig),
  AbFormIfream: markRaw(abFormIfreamConfig),
  AbToolbar: markRaw(AbToolbarConfig),
  AbIcoinButton: markRaw(AbIcoinButtonConfig),
  AbCustFormComponent: markRaw(AbCustFormComponent),
  AbCustomListComponent: markRaw(AbCustomListComponent),
  Test: markRaw(Test),
  AbPictureConfig: markRaw(AbPictureConfig),
  AbFilterConfig: markRaw(AbFilterConfig),
  AbBarEcharts: markRaw(AbEchartsConfig),
  AbPieEcharts: markRaw(AbEchartsConfig),
  AbLineEcharts: markRaw(AbEchartsConfig),
  AbAreaEcharts: markRaw(AbEchartsConfig),
  AbFunnelEcharts: markRaw(AbEchartsConfig),
  AbIndicatorCard: markRaw(AbIndicatorCardConfig),
  AbBpmIndicatorCardConfig: markRaw(AbBpmIndicatorCardConfig),
  AbGanttChartConfig: markRaw(AbGanttChartConfig),
  AbTodoTaskConfig: markRaw(AbTodoTaskConfig),
  AbMapConfig: markRaw(AbMapConfig),
  AbRichEditorConfig: markRaw(AbRichEditorConfig),
 // AbAlertConfig: markRaw(AbAlertConfig),
}
